---
- name: Install common software requirements
  apt: pkg={{ item }} state=installed
  with_items:
    - git
    - htop
    - vim
    - unzip
    - curl
    - sudo

- name: Create the sudo group
  group:
    name=sudo
    state=present

#- name: Create home directory folder structure
#  file: path=/home/{{ user_name }}/{{ item }}
#     state=directory
#     owner={{ user_name }}
#     group={{ user_name }}
#     mode=0700
#  with_items:
#     - src
#     - backups
#     - bin
#     - tmp
#
#- name: Copy a file
#  copy: src=10mb-file.bin dest=/home/{{ user_name }}/10mb-file.bin
#     owner={{ user_name }}
#     group={{ user_name }}
